# Generated by Django 5.2.13 on 2026-04-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('symptoms', models.TextField()),
                ('prevention', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='diseases/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
