# Generated by Django 5.2.13 on 2026-04-29 17:58

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='doctors/images/')),
                ('license_pdf', models.FileField(blank=True, null=True, upload_to='doctors/pdfs/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('diseases', models.ManyToManyField(blank=True, related_name='doctors', to='diseases.disease')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
